services:
  lite_version:
    build:
      context: .
      dockerfile: Dockerfile
      target: lite-app
    volumes:
      - ./inbox:/app/inbox
      - ./types:/app/types
      - ./out:/app/out
  extended_version:
      build:
        context: .
        dockerfile: Dockerfile
        target: extended-app
      volumes:
        - ./inbox:/app/inbox
        - ./types:/app/types
        - ./out:/app/out
